# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'BaseProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseProject
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources', '~> 3.0'
  pod 'Moya/RxSwift', '~> 11.0'
  pod 'ObjectMapper', '~> 3.3'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'JGProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'MJRefresh'
  pod 'ActionSheetPicker-3.0'
  pod 'FontAwesome.swift'
  pod 'NVActivityIndicatorView'
  
  pod 'AWSMobileClient', '~> 2.6.13'
  pod  'AWSPinpoint', '~> 2.6.13'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Fabric'
  pod 'Crashlytics'

end
